.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. tokyocoin_qt test_tokyocoin_qt
clean: FORCE
	$(MAKE) -C .. tokyocoin_qt_clean test_tokyocoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_tokyocoin_qt_check
tokyocoin-qt tokyocoin-qt.exe: FORCE
	 $(MAKE) -C .. tokyocoin_qt
